### ISSUE TITLE
First steps for clean development environment

### ISSUE THREAD

**Issue by Matt-1985** [Matt-1985/choicely#1]
## User story

As a developer i want to have a clean and structures workspace to work more efficient.

## Notes / Links / Further Description

-

## ToDos

- [x]  Setup repo in GitHub with ReadMe, MIT License and Node gitignore
- [x]  Clone locally
- [x]  Add package.json
- [x]  Add server.js and server starting script to package.json
- [x]  Setup project on Heroku and add read port from enviroment for the deployment
- [x]  Add prettier
- [x]  Add ES-Lint
- [x]  Add eslint-config-prettier
- [x]  Add lint-staged and husky
- [x]  Install Create React App to Client-Level
- [x]  Write eslintignore and the scripts for linting
- [x]  Add build-scripts to TOP-Level
- [x]  Add storybook and dependecies
- [x]  Build storybook
- [x]  Deploy on Heroku
- [x]  Check if deployment is working
- [x]  Add dotenv
