### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by Matt-1985** [Matt-1985/choicely#15]
## User story

As a developer i want my app to be used cross-platform to reach a wider audience.

## Notes / Links / Further Description

[PWA](https://create-react-app.dev/docs/making-a-progressive-web-app/)

## ToDos

- [x] read doc / watch tutorial
- [x] implement: yes or no?
- [x] if yes > implement step by step
