### ISSUE TITLE
Connect frontend with backend

### ISSUE THREAD

**Issue by Matt-1985** [Matt-1985/choicely#16]
## User story

As a user i want my choices and desicions quick and accurate on the screen to help me make mine.

## ToDos

- [x] Implement filter route from selectbox to API
- [ ] Implement get route from button to API
- [x] Implement connection from API to cards element
