### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Matt-1985** [Matt-1985/choicely#17]
## User story

As a developer i want my code as simple and clean as possible to guarantee that other developer can read and understand my code.

## ToDos

- [ ] Analyse 
- [ ] Improve exception handling
- [ ] Exchange (Favicon, font, titles, metadata etc.)
- [ ] Send to review
