### ISSUE TITLE
Build Fake data

### ISSUE THREAD

**Issue by Matt-1985** [Matt-1985/choicely#3]
## User story

As user i want to have the possibility to filter my search to get a customized decision.

## Notes / Links / Further Description

MongoDB !

## ToDos

- [x] Brainstorm which Data is needed
- [x] Creating Mockdata in db.json
- [x] Implement API routes for GET
- [x] Test in Postman
