### ISSUE TITLE
First Navigation Elements

### ISSUE THREAD

**Issue by Matt-1985** [Matt-1985/choicely#4]
## User story

As a Developer i want to build single components to work more efficent.

## ToDos

- [x] Install "styled components"
- [x] Set up global.css
- [x] build splash page
- [x] build navigation buttons
- [x] build "Auswahlfeld 1"
- [x] build "Main Auswahlfeld"
